CREATE TABLE `enhancementJobs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`title` varchar(255) NOT NULL,
	`inputVideoUrl` varchar(1024) NOT NULL,
	`inputVideoKey` varchar(512) NOT NULL,
	`inputVideoDuration` int NOT NULL,
	`inputVideoSize` int NOT NULL,
	`style` varchar(64) NOT NULL,
	`musicEnabled` boolean NOT NULL DEFAULT true,
	`captionsEnabled` boolean NOT NULL DEFAULT true,
	`analysisStatus` enum('pending','processing','completed','failed') NOT NULL DEFAULT 'pending',
	`analysisData` longtext,
	`speechSegments` longtext,
	`sceneSegments` longtext,
	`detectedMood` varchar(128),
	`musicGenerationStatus` enum('pending','processing','completed','failed') NOT NULL DEFAULT 'pending',
	`musicUrl` varchar(1024),
	`musicKey` varchar(512),
	`sunoTaskId` varchar(255),
	`captionSegments` longtext,
	`renderStatus` enum('pending','processing','completed','failed') NOT NULL DEFAULT 'pending',
	`outputUrl16x9` varchar(1024),
	`outputKey16x9` varchar(512),
	`outputUrl9x16` varchar(1024),
	`outputKey9x16` varchar(512),
	`creditCost` int NOT NULL DEFAULT 1,
	`errorMessage` text,
	`enhancementStatus` enum('draft','analyzing','generating','rendering','completed','failed') NOT NULL DEFAULT 'draft',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `enhancementJobs_id` PRIMARY KEY(`id`)
);
