CREATE TABLE `renderManifests` (
	`id` int AUTO_INCREMENT NOT NULL,
	`jobId` int NOT NULL,
	`schemaVersion` varchar(16) NOT NULL DEFAULT '1.0',
	`totalScenes` int NOT NULL DEFAULT 0,
	`approvedScenes` int NOT NULL DEFAULT 0,
	`failedScenes` int NOT NULL DEFAULT 0,
	`pendingScenes` int NOT NULL DEFAULT 0,
	`manifestJson` longtext,
	`manifestPipelineState` enum('draft','storyboard_ready','rendering','validation','correction','assembly_ready','assembling','delivered','failed','paused') NOT NULL DEFAULT 'draft',
	`totalProviderSpendUsd` decimal(8,4) NOT NULL DEFAULT '0',
	`lastUpdatedBy` varchar(64),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `renderManifests_id` PRIMARY KEY(`id`),
	CONSTRAINT `renderManifests_jobId_unique` UNIQUE(`jobId`)
);
--> statement-breakpoint
CREATE TABLE `sceneAuditLog` (
	`id` int AUTO_INCREMENT NOT NULL,
	`sceneId` int NOT NULL,
	`jobId` int NOT NULL,
	`fromState` varchar(64),
	`toState` varchar(64) NOT NULL,
	`triggeredBy` varchar(64) NOT NULL,
	`provider` varchar(64),
	`providerTaskId` varchar(255),
	`providerModel` varchar(128),
	`promptSnapshot` text,
	`negativePromptSnapshot` text,
	`seedValue` varchar(64),
	`validationGate` varchar(64),
	`validationPassed` boolean,
	`validationFailureCategory` varchar(64),
	`validationMetricsJson` text,
	`retryNumber` int NOT NULL DEFAULT 0,
	`retryReason` text,
	`rawVideoUrl` varchar(1024),
	`correctedVideoUrl` varchar(1024),
	`screenshotUrl` varchar(1024),
	`providerCostUsd` decimal(6,4) NOT NULL DEFAULT '0',
	`errorMessage` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `sceneAuditLog_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `sceneWebhookEvents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`provider` varchar(64) NOT NULL,
	`providerTaskId` varchar(255) NOT NULL,
	`eventType` varchar(64) NOT NULL,
	`payloadHash` varchar(64),
	`processed` boolean NOT NULL DEFAULT false,
	`processedAt` timestamp,
	`processingError` text,
	`processingAttempts` int NOT NULL DEFAULT 0,
	`rawPayloadJson` longtext,
	`resolvedSceneId` int,
	`resolvedJobId` int,
	`signatureVerified` boolean NOT NULL DEFAULT false,
	`receivedAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `sceneWebhookEvents_id` PRIMARY KEY(`id`)
);
