/**
 * AI Animation Maker — SEO Landing Page
 * Route: /ai-animation-maker
 *
 * Targets:
 *  - AI animation maker
 *  - Animated kids videos
 *  - Stylised 3D animation
 *  - Storybook animation
 *  - Short animated video creation
 *
 * NO render/provider/API calls on this page.
 * Pure landing page — CTA drives to /kids-video (WizAnimate tool).
 */
import { useState } from "react";
import { useSEO } from "@/hooks/useSEO";
import { useAuth } from "@/_core/hooks/useAuth";
import { NavLink } from "@/components/NavLink";
import BackButton from "@/components/BackButton";
import AuthGate from "@/components/AuthGate";
import { mp } from "@/lib/mixpanel";
import ShowcaseVideoSection from "@/components/ShowcaseVideoSection";

// ── Asset constants ───────────────────────────────────────────────────────────
const CDN = "/manus-storage";
const WIZAI_LOGO = "/manus-storage/wizai-logo-premium-transparent_ff33f09f.webp";
const WIZANIMATE_LOGO = `${CDN}/wizanimate-logo-new_a84f9808.png`;
const WIZCREATE_LOGO = `${CDN}/wizcreate-logo-new_85a25756.png`;
const WIZSOUND_LOGO = `${CDN}/wizsound-logo-new_c5cced65.png`;

// Animation style showcase images (all existing CDN assets)
const ANIMATION_STYLES = [
  {
    id: "pixar3d",
    label: "Stylised 3D",
    desc: "Vibrant, expressive 3D characters and worlds",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663500868908/ALJHDNsuNA7bExFuoQZUsx/kids-style-pixar3d-NTKiSeKEePTZ64eY2dVzqo.webp",
    tag: "Most popular",
  },
  {
    id: "storybook",
    label: "Storybook",
    desc: "Illustrated fairy-tale style — timeless and magical",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663500868908/ALJHDNsuNA7bExFuoQZUsx/kids-style-storybook-6Mx6JpiaevStuWQin5HEod.webp",
    tag: "Kids favourite",
  },
  {
    id: "disney",
    label: "Magical Cinematic",
    desc: "Enchanted, cinematic animation with sweeping visuals",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663500868908/ALJHDNsuNA7bExFuoQZUsx/kids-style-disney-Ps9izwb4mjU6QbawNJEZ9C.webp",
    tag: null,
  },
  {
    id: "anime",
    label: "Anime-Inspired",
    desc: "Expressive Japanese animation style with vivid detail",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663500868908/ALJHDNsuNA7bExFuoQZUsx/kids-style-anime-iGDqmnXkbWropdM7MmSEPe.webp",
    tag: null,
  },
  {
    id: "cartoon",
    label: "Classic Cartoon",
    desc: "Colourful, fun, family-friendly classic animation",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663500868908/ALJHDNsuNA7bExFuoQZUsx/kids-style-cartoon-g3SpesBvzubV27y7fGnGuq.webp",
    tag: null,
  },
  {
    id: "claymation",
    label: "Clay Animation",
    desc: "Playful, tactile clay-style handcrafted look",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663500868908/ALJHDNsuNA7bExFuoQZUsx/kids-style-claymation-ihKTHjJ2NDdPcS9ekpiaNN.webp",
    tag: null,
  },
];

const USE_CASES = [
  {
    icon: "play",
    title: "Kids YouTube Channels",
    desc: "Create engaging animated intros, story episodes, and educational content for young audiences — without hiring an animation studio.",
  },
  {
    icon: "book",
    title: "Storybook & Fairytale Videos",
    desc: "Bring illustrated stories to life with narration-synced animation. Perfect for bedtime stories, school projects, and family content.",
  },
  {
    icon: "star",
    title: "Stylised 3D Short Films",
    desc: "Produce cinematic 3D animated shorts from a single text prompt. Characters, environments, lighting — all generated by AI.",
  },
  {
    icon: "learn",
    title: "Educational Explainers",
    desc: "Turn complex topics into animated explainer videos that hold attention. Ideal for teachers, tutors, and e-learning creators.",
  },
];

const HOW_IT_WORKS = [
  {
    step: "01",
    title: "Describe your animation",
    desc: "Tell WIZ AI what you want — characters, setting, mood, and story. Add a title, theme, or even a script.",
    img: "/manus-storage/hiw-step1-choose_1102ddee.jpg",
  },
  {
    step: "02",
    title: "Choose your animation style",
    desc: "Pick from Stylised 3D, Storybook, Anime, Classic Cartoon, Magical Cinematic, or Clay Animation.",
    img: "/manus-storage/hiw-step2-storyboard_21e66052.jpg",
  },
  {
    step: "03",
    title: "Preview every scene",
    desc: "WizCreate™ builds a full storyboard. Review, edit, and refine each scene before building a single frame.",
    img: "/manus-storage/hiw-step3-preview_e536f5b1.jpg",
  },
  {
    step: "04",
    title: "Build and download",
    desc: "Export your finished animation in HD or 4K with WizSound™ audio mastering built in. Ready to publish.",
    img: "/manus-storage/hiw-step4-export_68c87f9e.jpg",
  },
];

const ANIMATION_USE_CASES = [
  {
    title: "Kids Content",
    desc: "Create animated intros, story episodes, and educational content in Stylised 3D or Storybook styles.",
    icon: "\u2728",
  },
  {
    title: "YouTube Animation",
    desc: "Build animated shorts, channel intros, and visual stories without complex animation software.",
    icon: "\ud83c\udfac",
  },
  {
    title: "Story Illustration",
    desc: "Transform written stories into illustrated animated scenes with consistent characters and styles.",
    icon: "\ud83d\udcd6",
  },
];

const FAQS = [
  {
    q: "Do I need any animation or design experience?",
    a: "None at all. WIZ AI handles everything — storyboarding, character generation, scene composition, and audio mastering. You just describe what you want.",
  },
  {
    q: "What animation styles are available?",
    a: "Six styles: Stylised 3D, Storybook, Magical Cinematic, Anime-Inspired, Classic Cartoon, and Clay Animation. More styles are added regularly.",
  },
  {
    q: "How long does it take to create an animated video?",
    a: "Storyboard generation takes seconds. Building a full animated video typically takes 3–8 minutes depending on length and quality setting.",
  },
  {
    q: "Can I add my own audio or narration?",
    a: "Yes. You can upload your own audio track, narration, or music and WIZ AI will sync the animation to it automatically.",
  },
  {
    q: "What video lengths are supported?",
    a: "From short 5-second clips up to 96-second full animated videos (12 scenes × 8 seconds each) on the Pro plan. Longer formats are in development.",
  },
  {
    q: "Is the output watermark-free?",
    a: "Yes. All paid plans produce watermark-free exports. The free trial includes one video with no watermark.",
  },
];

const FEATURES = [
  {
    logo: WIZANIMATE_LOGO,
    title: "WizAnimate™ Engine",
    desc: "Our proprietary animation engine generates fluid, stylistically consistent characters and environments from a single text prompt.",
  },
  {
    logo: WIZCREATE_LOGO,
    title: "WizCreate™ Storyboarding",
    desc: "AI-powered storyboard generation breaks your idea into scenes with timing, composition, and character direction — automatically.",
  },
  {
    logo: WIZSOUND_LOGO,
    title: "WizSound™ Audio Mastering",
    desc: "Every animation is paired with high-quality audio mastering. Upload your own track or let WIZ AI enhance the audio.",
  },
  {
    logo: WIZANIMATE_LOGO,
    title: "Character Lock System",
    desc: "Maintain consistent character appearance across every scene. Upload a reference image and WIZ AI keeps your character recognisable.",
  },
  {
    logo: WIZCREATE_LOGO,
    title: "Scene-by-Scene Editing",
    desc: "Review and edit every scene before building. Change prompts, swap styles, or regenerate individual scenes without starting over.",
  },
  {
    logo: WIZSOUND_LOGO,
    title: "HD & 4K Export",
    desc: "Export in Standard 720p, HD 1080p, or cinema-grade 4K. All exports are watermark-free on paid plans.",
  },
];

// ── Component ─────────────────────────────────────────────────────────────────
export default function AiAnimationMaker() {
  useSEO({
    title: "AI Animation Maker — Create Animated Videos Online | WIZ AI",
    path: "/ai-animation-maker",
    description: "Create stunning animated videos with AI. Choose from Stylised 3D, Storybook, Anime, and more. Perfect for kids channels, animated shorts, and storybook videos. No experience needed.",
  });

  const { isAuthenticated } = useAuth();
  const [showAuthGate, setShowAuthGate] = useState(false);
  const [openFaq, setOpenFaq] = useState<number | null>(null);

  const handleCTA = (source: string) => {
    mp.startCreatingClicked(source);
    if (isAuthenticated) {
      window.location.href = "/products/wizanimate";
    } else {
      setShowAuthGate(true);
    }
  };

  return (
    <div className="min-h-screen studio-bg text-white">
      <AuthGate
        open={showAuthGate}
        onClose={() => setShowAuthGate(false)}
        featureName="create your animated video"
      />

      {/* ── Navigation ─────────────────────────────────────────────────────── */}
      <nav className="studio-header sticky top-0 z-50 backdrop-blur-xl">
        <div className="max-w-6xl mx-auto px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-4">
            <BackButton fallback="/" label="Back to Home" />
            <NavLink href="/" className="hidden md:flex items-center">
              <img
                src={WIZAI_LOGO}
                alt="WIZ AI"
                className="h-[7.3rem] w-auto object-contain transition-all duration-300 hover:scale-105 hover:brightness-110"
              />
            </NavLink>
          </div>
          <div className="hidden md:flex items-center gap-1">
            {[
              { label: "Home", href: "/" },
              { label: "WizAnimate", href: "/products/wizanimate" },
              { label: "WizVideo", href: "/music-video" },
              { label: "Pricing", href: "/pricing" },
              { label: "Help", href: "/help" },
            ].map((link) => (
              <NavLink
                key={link.label}
                href={link.href}
                className="px-4 py-2 text-sm text-[#a1a1aa] hover:text-white rounded-lg transition-all duration-200 font-medium hover:scale-105 hover:-translate-y-0.5 inline-block"
              >
                {link.label}
              </NavLink>
            ))}
          </div>
          <div className="flex items-center gap-3">
            {isAuthenticated ? (
              <NavLink
                href="/products/wizanimate"
                className="px-5 py-2.5 bg-[--color-gold] text-black text-sm font-bold rounded-xl hover:brightness-110 transition-all"
                onClick={() => mp.startCreatingClicked("nav_cta")}
              >
                Start Animating
              </NavLink>
            ) : (
              <button
                onClick={() => handleCTA("nav_cta")}
                className="px-5 py-2.5 bg-[--color-gold] text-black text-sm font-bold rounded-xl hover:brightness-110 transition-all cursor-pointer"
              >
                Try Free
              </button>
            )}
          </div>
        </div>
      </nav>

      {/* ── Hero ───────────────────────────────────────────────────────────── */}
      <section className="relative pt-24 pb-20 px-6 overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-br from-[#1a0a2e] via-[#0a0a0a] to-[#0a1a0a] pointer-events-none" />
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[800px] h-[400px] bg-[--color-gold]/[0.06] rounded-full blur-[120px] pointer-events-none" />

        <div className="relative max-w-5xl mx-auto text-center">
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full border border-[--color-gold]/30 bg-[--color-gold]/[0.08] text-[--color-gold] text-xs font-semibold tracking-wide uppercase mb-8">
            <img src={WIZANIMATE_LOGO} alt="" className="h-4 w-4 object-contain" />
            WizAnimate™ — AI Animation Engine
          </div>

          <h1 className="text-5xl md:text-7xl font-bold tracking-tight mb-6 leading-[1.05]">
            <span className="text-white">Create Stunning</span>
            <br />
            <span
              className="bg-clip-text text-transparent"
              style={{ backgroundImage: "linear-gradient(135deg, #c8a84b 0%, #f0d080 40%, #c8a84b 100%)" }}
            >
              AI Animated Videos
            </span>
            <br />
            <span className="text-white">in Minutes</span>
          </h1>

          <p className="text-lg md:text-xl text-[#a1a1aa] max-w-2xl mx-auto mb-10 leading-relaxed">
            From kids' storybook animation to stylised 3D shorts — describe your idea, choose a style, and WIZ AI generates a full animated video. No animation skills required.
          </p>

          <div className="flex flex-col sm:flex-row items-center justify-center gap-4 mb-12">
            <button
              onClick={() => handleCTA("hero_primary")}
              className="px-8 py-4 bg-[--color-gold] text-black font-bold text-base rounded-xl hover:brightness-110 transition-all hover:scale-105 shadow-[0_0_30px_rgba(200,168,75,0.3)] cursor-pointer"
            >
              Start Creating Free →
            </button>
            <NavLink
              href="/pricing"
              className="px-8 py-4 border border-white/20 text-white font-medium text-base rounded-xl hover:border-white/40 hover:bg-white/[0.04] transition-all"
            >
              View Pricing
            </NavLink>
          </div>

          <div className="flex flex-wrap items-center justify-center gap-6 text-sm text-[#71717a]">
            <span className="flex items-center gap-1.5">
              <span className="text-[--color-gold]">✓</span> Free trial — no credit card
            </span>
            <span className="flex items-center gap-1.5">
              <span className="text-[--color-gold]">✓</span> 6 animation styles
            </span>
            <span className="flex items-center gap-1.5">
              <span className="text-[--color-gold]">✓</span> HD &amp; 4K export
            </span>
            <span className="flex items-center gap-1.5">
              <span className="text-[--color-gold]">✓</span> Preview before you build
            </span>
          </div>
        </div>
      </section>

      {/* ── Animation Style Showcase ────────────────────────────────────────── */}
      <section className="py-20 px-6">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-14">
            <h2 className="text-3xl md:text-4xl font-bold text-white mb-4">
              Six Distinct Animation Styles
            </h2>
            <p className="text-[#a1a1aa] text-lg max-w-xl mx-auto">
              Every style is a complete visual world. Pick the one that matches your story.
            </p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5">
            {ANIMATION_STYLES.map((style) => (
              <div
                key={style.id}
                className="group relative rounded-2xl overflow-hidden border border-white/[0.08] hover:border-[--color-gold]/30 transition-all duration-300 cursor-pointer"
                onClick={() => handleCTA(`style_card_${style.id}`)}
              >
                <div className="aspect-[4/3] overflow-hidden">
                  <img
                    src={style.image}
                    alt={`${style.label} animation style`}
                    className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
                    loading="lazy"
                  />
                </div>
                <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/20 to-transparent" />
                {style.tag && (
                  <div className="absolute top-3 right-3 px-2.5 py-1 bg-[--color-gold] text-black text-xs font-bold rounded-full">
                    {style.tag}
                  </div>
                )}
                <div className="absolute bottom-0 left-0 right-0 p-5">
                  <h3 className="text-white font-bold text-lg mb-1">{style.label}</h3>
                  <p className="text-[#a1a1aa] text-sm">{style.desc}</p>
                </div>
              </div>
            ))}
          </div>

          <div className="text-center mt-10">
            <button
              onClick={() => handleCTA("styles_section_cta")}
              className="px-8 py-4 bg-[--color-gold] text-black font-bold text-base rounded-xl hover:brightness-110 transition-all hover:scale-105 cursor-pointer"
            >
              Try All Styles Free →
            </button>
          </div>
        </div>
      </section>

      {/* ── Use Cases ──────────────────────────────────────────────────────── */}
      <section className="py-20 px-6 bg-[#0f0f0f]">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-14">
            <h2 className="text-3xl md:text-4xl font-bold text-white mb-4">
              Built for Every Animation Creator
            </h2>
            <p className="text-[#a1a1aa] text-lg max-w-xl mx-auto">
              Whether you're making kids' content, short films, or educational videos — WIZ AI has you covered.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {USE_CASES.map((uc, i) => (
              <div
                key={i}
                className="p-7 rounded-2xl border border-white/[0.08] bg-[#141414] hover:border-[--color-gold]/20 transition-all duration-300"
              >
                <div className="w-12 h-12 rounded-xl bg-white/5 border border-white/10 flex items-center justify-center mb-4">
                  <svg className="w-6 h-6 text-[--color-gold]" viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
                    {uc.icon === "play" && <path d="M6.5 4.5l9 5.5-9 5.5V4.5z" fill="currentColor" stroke="none" />}
                    {uc.icon === "book" && <><path d="M3 3h5c1.1 0 2 .9 2 2v12l-1-1H3V3z" /><path d="M17 3h-5c-1.1 0-2 .9-2 2v12l1-1h6V3z" /></>}
                    {uc.icon === "star" && <path d="M10 2l2.4 4.8 5.3 1-3.8 3.8.9 5.4-4.8-2.5-4.8 2.5.9-5.4L2.3 7.8l5.3-1L10 2z" fill="currentColor" stroke="none" />}
                    {uc.icon === "learn" && <><circle cx="10" cy="6" r="3" /><path d="M4 17v-2c0-2.2 2.7-4 6-4s6 1.8 6 4v2" /></>}
                  </svg>
                </div>
                <h3 className="text-white font-bold text-xl mb-3">{uc.title}</h3>
                <p className="text-[#a1a1aa] leading-relaxed mb-5">{uc.desc}</p>
                <button
                  onClick={() => handleCTA(`use_case_${i}`)}
                  className="text-[--color-gold] text-sm font-semibold hover:brightness-110 transition-all cursor-pointer flex items-center gap-1.5"
                >
                  Start creating →
                </button>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── How It Works ───────────────────────────────────────────────────── */}
      <section className="py-20 px-6">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-14">
            <h2 className="text-3xl md:text-4xl font-bold text-white mb-4">
              From Idea to Animated Video in 4 Steps
            </h2>
            <p className="text-[#a1a1aa] text-lg max-w-xl mx-auto">
              No timeline. No keyframes. No editing software. Just describe, preview, and export.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            {HOW_IT_WORKS.map((step, i) => (
              <div key={i} className="flex gap-5">
                <div className="flex-shrink-0 w-12 h-12 rounded-xl bg-[--color-gold]/10 border border-[--color-gold]/20 flex items-center justify-center">
                  <span className="text-[--color-gold] font-bold text-sm">{step.step}</span>
                </div>
                <div className="flex-1">
                  <div className="aspect-video rounded-xl overflow-hidden mb-4 border border-white/[0.06]">
                    <img
                      src={step.img}
                      alt={step.title}
                      className="w-full h-full object-cover"
                      loading="lazy"
                    />
                  </div>
                  <h3 className="text-white font-bold text-lg mb-2">{step.title}</h3>
                  <p className="text-[#a1a1aa] leading-relaxed">{step.desc}</p>
                </div>
              </div>
            ))}
          </div>

          <div className="text-center mt-12">
            <button
              onClick={() => handleCTA("how_it_works_cta")}
              className="px-8 py-4 bg-[--color-gold] text-black font-bold text-base rounded-xl hover:brightness-110 transition-all hover:scale-105 cursor-pointer"
            >
              Create Your First Animation →
            </button>
          </div>
        </div>
      </section>

      {/* ── Feature Highlights ─────────────────────────────────────────────── */}
      <section className="py-20 px-6 bg-[#0f0f0f]">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-14">
            <h2 className="text-3xl md:text-4xl font-bold text-white mb-4">
              Everything You Need to Animate
            </h2>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
            {FEATURES.map((feat, i) => (
              <div
                key={i}
                className="p-6 rounded-2xl border border-white/[0.08] bg-[#141414] hover:border-[--color-gold]/20 transition-all duration-300"
              >
                <img src={feat.logo} alt="" className="h-10 w-10 object-contain mb-4" />
                <h3 className="text-white font-bold text-base mb-2">{feat.title}</h3>
                <p className="text-[#a1a1aa] text-sm leading-relaxed">{feat.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>      {/* ── Use Cases ───────────────────────────────────────────────────────────── */}
      <section className="py-20 px-6">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-14">
            <h2 className="text-3xl md:text-4xl font-bold text-white mb-4">
              What you can animate with WIZ AI
            </h2>
            <p className="text-[#a1a1aa] text-sm max-w-lg mx-auto">
              Example use cases for the AI Animation Maker. Real customer stories will be added once creators begin publishing.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {ANIMATION_USE_CASES.map((uc, i) => (
              <div
                key={i}
                className="p-6 rounded-2xl border border-white/[0.08] bg-[#0f0f0f] hover:border-white/15 transition-all"
              >
                <span className="w-10 h-10 rounded-xl bg-white/5 border border-white/10 flex items-center justify-center mb-4">
                  <svg className="w-5 h-5 text-[--color-gold]" viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
                    {uc.icon === "play" && <path d="M6.5 4.5l9 5.5-9 5.5V4.5z" fill="currentColor" stroke="none" />}
                    {uc.icon === "book" && <><path d="M3 3h5c1.1 0 2 .9 2 2v12l-1-1H3V3z" /><path d="M17 3h-5c-1.1 0-2 .9-2 2v12l1-1h6V3z" /></>}
                    {uc.icon === "star" && <path d="M10 2l2.4 4.8 5.3 1-3.8 3.8.9 5.4-4.8-2.5-4.8 2.5.9-5.4L2.3 7.8l5.3-1L10 2z" fill="currentColor" stroke="none" />}
                    {uc.icon === "learn" && <><circle cx="10" cy="6" r="3" /><path d="M4 17v-2c0-2.2 2.7-4 6-4s6 1.8 6 4v2" /></>}
                  </svg>
                </span>
                <h3 className="text-white font-bold text-lg mb-2">{uc.title}</h3>
                <p className="text-[#a1a1aa] text-sm leading-relaxed">{uc.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>    {/* ── Pricing CTA ────────────────────────────────────────────────────── */}
      <section className="py-20 px-6 bg-[#0f0f0f]">
        <div className="max-w-3xl mx-auto text-center">
          <h2 className="text-3xl md:text-4xl font-bold text-white mb-4">
            Start Animating Today
          </h2>
          <p className="text-[#a1a1aa] text-lg mb-8">
            Free trial included. No credit card required. One free animated video to get started.
          </p>

          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-10">
            {[
              { name: "Free Trial", price: "£0", detail: "1 animated video" },
              { name: "Starter", price: "£29/mo", detail: "2 videos · 8 scenes each" },
              { name: "Creator", price: "£79/mo", detail: "6 videos · 4K export", popular: true },
            ].map((plan, i) => (
              <div
                key={i}
                className={`p-5 rounded-xl border transition-all ${
                  plan.popular
                    ? "border-[--color-gold]/50 bg-[--color-gold]/[0.06]"
                    : "border-white/[0.08] bg-[#141414]"
                }`}
              >
                {plan.popular && (
                  <div className="text-[--color-gold] text-xs font-bold uppercase tracking-wide mb-2">
                    Most Popular
                  </div>
                )}
                <div className="text-white font-bold text-base mb-1">{plan.name}</div>
                <div className="text-[--color-gold] font-bold text-xl mb-1">{plan.price}</div>
                <div className="text-[#71717a] text-xs">{plan.detail}</div>
              </div>
            ))}
          </div>

          <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
            <button
              onClick={() => handleCTA("pricing_section_primary")}
              className="px-8 py-4 bg-[--color-gold] text-black font-bold text-base rounded-xl hover:brightness-110 transition-all hover:scale-105 shadow-[0_0_30px_rgba(200,168,75,0.25)] cursor-pointer"
            >
              Start Free →
            </button>
            <NavLink
              href="/pricing"
              className="px-8 py-4 border border-white/20 text-white font-medium text-base rounded-xl hover:border-white/40 hover:bg-white/[0.04] transition-all"
            >
              Compare All Plans
            </NavLink>
          </div>
        </div>
      </section>

      {/* ── FAQ ────────────────────────────────────────────────────────────── */}
      <section className="py-20 px-6">
        <div className="max-w-3xl mx-auto">
          <div className="text-center mb-14">
            <h2 className="text-3xl md:text-4xl font-bold text-white mb-4">
              Frequently Asked Questions
            </h2>
          </div>

          <div className="space-y-3">
            {FAQS.map((faq, i) => (
              <div
                key={i}
                className="border border-white/[0.08] rounded-xl overflow-hidden"
              >
                <button
                  onClick={() => setOpenFaq(openFaq === i ? null : i)}
                  className="w-full flex items-center justify-between px-6 py-5 text-left hover:bg-white/[0.03] transition-all cursor-pointer"
                >
                  <span className="text-white font-medium pr-4">{faq.q}</span>
                  <span className="text-[--color-gold] flex-shrink-0 text-lg">
                    {openFaq === i ? "−" : "+"}
                  </span>
                </button>
                {openFaq === i && (
                  <div className="px-6 pb-5 text-[#a1a1aa] leading-relaxed text-sm border-t border-white/[0.06]">
                    <div className="pt-4">{faq.a}</div>
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Final CTA ──────────────────────────────────────────────────────── */}
      <section className="py-24 px-6 relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-br from-[#1a0a2e] via-[#0a0a0a] to-[#0a1a0a] pointer-events-none" />
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[300px] bg-[--color-gold]/[0.08] rounded-full blur-[100px] pointer-events-none" />

        <div className="relative max-w-3xl mx-auto text-center">
          <img src={WIZANIMATE_LOGO} alt="WizAnimate" className="h-16 w-16 object-contain mx-auto mb-6" />
          <h2 className="text-4xl md:text-5xl font-bold text-white mb-4">
            Your Animation Starts Here
          </h2>
          <p className="text-[#a1a1aa] text-lg mb-10">
            Join creators worldwide making animated videos with WIZ AI. Start free — no credit card needed.
          </p>
          <button
            onClick={() => handleCTA("final_cta")}
            className="px-10 py-5 bg-[--color-gold] text-black font-bold text-lg rounded-xl hover:brightness-110 transition-all hover:scale-105 shadow-[0_0_40px_rgba(200,168,75,0.35)] cursor-pointer"
          >
            Create Your First Animation Free →
          </button>
        </div>
      </section>

      {/* ── Showcase ─────────────────────────────────────────────────────── */}
      <ShowcaseVideoSection
        title="See what WIZ AI animation looks like"
        subtitle="Animation showcase"
        description="Every animation created from a text prompt. No software, no timeline, no experience needed."
        ctaLabel="Create Your First Animation"
        ctaHref="/products/wizanimate"
        items={[
          {
            id: 30003,
            title: "Star Quest — Kids Channel Intro",
            category: "Stylised 3D",
            posterUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663500868908/ALJHDNsuNA7bExFuoQZUsx/showcase-kids-fxm6wHeSYgLJUHFdQPtC6r.webp",
            videoUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663500868908/ALJHDNsuNA7bExFuoQZUsx/showcase-kids_d49d86f8.mp4",
            description: "Cinematic 3D animation for a kids YouTube channel. Generated from a character description and theme prompt.",
          },
          {
            id: 30005,
            title: "The Enchanted Forest — Story Animation",
            category: "Storybook Animation",
            posterUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663500868908/ALJHDNsuNA7bExFuoQZUsx/showcase-story-USepA6hkPxe97oTtpWXhtt.webp",
            videoUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663500868908/ALJHDNsuNA7bExFuoQZUsx/showcase-story_ffc51308.mp4",
            description: "A magical forest story with cinematic lighting and character animation. Generated from a narrative prompt.",
          },
          {
            id: 30004,
            title: "Cherry Blossom — Anime Style",
            category: "Anime-Inspired",
            posterUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663500868908/ALJHDNsuNA7bExFuoQZUsx/showcase-anime-gdkPWj4zZ3wPdwmswMeaY9.webp",
            videoUrl: "https://d2xsxph8kpxj0f.cloudfront.net/310519663500868908/ALJHDNsuNA7bExFuoQZUsx/showcase-anime_36099b49.mp4",
            description: "Fluid anime-style visuals with cherry blossom transitions. Generated entirely from a mood and colour palette prompt.",
          },
        ]}
      />

      {/* ── Footer ─────────────────────────────────────────────────────────── */}
      <footer className="border-t border-white/[0.06] py-10 px-6">
        <div className="max-w-6xl mx-auto flex flex-col md:flex-row items-center justify-between gap-6">
          <NavLink href="/">
            <img src={WIZAI_LOGO} alt="WIZ AI" className="h-16 w-auto object-contain" />
          </NavLink>
          <div className="flex flex-wrap items-center justify-center gap-6 text-sm text-[#71717a]">
            <NavLink href="/" className="hover:text-white transition-colors">Home</NavLink>
            <NavLink href="/products/wizanimate" className="hover:text-white transition-colors">WizAnimate</NavLink>
            <NavLink href="/music-video" className="hover:text-white transition-colors">WizVideo</NavLink>
            <NavLink href="/ai-video-generator" className="hover:text-white transition-colors">AI Video Generator</NavLink>
            <NavLink href="/pricing" className="hover:text-white transition-colors">Pricing</NavLink>
            <NavLink href="/help" className="hover:text-white transition-colors">Help</NavLink>
            <NavLink href="/privacy" className="hover:text-white transition-colors">Privacy</NavLink>
            <NavLink href="/terms" className="hover:text-white transition-colors">Terms</NavLink>
            <NavLink href="/cookie-policy" className="hover:text-white transition-colors">Cookies</NavLink>
            <button onClick={() => window.dispatchEvent(new CustomEvent('wiz:open-cookie-settings'))} className="hover:text-white transition-colors bg-transparent border-0 p-0 cursor-pointer text-sm text-[#71717a]">Cookie Settings</button>
          </div>
          <p className="text-[#52525b] text-xs">© 2026 WIZ AI. All rights reserved.</p>
        </div>
      </footer>
    </div>
  );
}
