import { Link } from "wouter";
const WIZVID_LOGO_FULL = "https://d2xsxph8kpxj0f.cloudfront.net/310519663500868908/ALJHDNsuNA7bExFuoQZUsx/wizvid-logo-cropped_86dbad19.png";

export default function Terms() {
  return (
    <div className="min-h-screen bg-[#0f0f0f] text-white">
      <nav className="sticky top-0 z-50 bg-[#0f0f0f]/95 backdrop-blur-xl border-b border-white/8">
        <div className="max-w-4xl mx-auto px-6 py-4 flex items-center justify-between">
          <Link href="/" className="flex items-center">
            <img src={WIZVID_LOGO_FULL} alt="WizVid" className="h-12 w-auto object-contain transition-all duration-300 hover:scale-105 hover:brightness-110" />
          </Link>
          <Link href="/" className="text-sm text-[#a1a1aa] hover:text-white transition-colors">← Back to Home</Link>
        </div>
      </nav>

      <main className="max-w-4xl mx-auto px-6 py-16">
        <div className="mb-10">
          <h1 className="text-4xl font-extrabold tracking-tight mb-3">Terms of Service</h1>
          <p className="text-[#a1a1aa] text-sm">Last updated: 9 April 2025</p>
        </div>

        <div className="prose prose-invert max-w-none space-y-8 text-[#d4d4d8] leading-relaxed">
          <section>
            <h2 className="text-xl font-bold text-white mb-3">1. Acceptance of Terms</h2>
            <p>By accessing or using WizVid ("the Service") at <strong>www.wizvid.ai</strong>, you agree to be bound by these Terms of Service. If you do not agree, please do not use the Service.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">2. Eligibility</h2>
            <p>You must be at least 13 years old to use WizVid. By using the Service, you represent that you meet this requirement. Users under 18 must have parental consent.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">3. Your Account</h2>
            <p>You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. Notify us immediately at <a href="mailto:support@wizvid.ai" className="text-purple-400 hover:text-purple-300 underline">support@wizvid.ai</a> if you suspect unauthorised access.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">4. Acceptable Use</h2>
            <p>You agree not to use WizVid to:</p>
            <ul className="list-disc pl-6 space-y-2 mt-2">
              <li>Create content that is illegal, defamatory, harassing, or infringes third-party intellectual property rights.</li>
              <li>Generate deepfakes of real individuals without their consent.</li>
              <li>Attempt to reverse-engineer, scrape, or exploit the platform's AI systems.</li>
              <li>Circumvent usage limits, credits, or subscription restrictions.</li>
              <li>Use the Service for any automated bulk generation without prior written consent.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">5. Content Ownership and AI Output</h2>
            <p><strong>Your input content:</strong> You retain ownership of any audio, images, or text you upload to WizVid.</p>
            <p className="mt-2"><strong>AI-generated output:</strong> Videos generated by WizVid are provided to you under a non-exclusive licence. You may use, share, and monetise AI-generated videos for personal and commercial purposes, subject to the following:</p>
            <ul className="list-disc pl-6 space-y-2 mt-2">
              <li>You must not claim that AI-generated content was created entirely by a human in contexts where that distinction is legally or ethically required.</li>
              <li>WizVid retains the right to use anonymised, aggregated output data for service improvement.</li>
              <li>We do not guarantee that AI-generated content is free from third-party intellectual property claims. You are responsible for ensuring your use complies with applicable laws.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">6. Credits and Subscriptions</h2>
            <p>WizVid operates on a credit-based system. Credits are consumed when you render videos. Unused credits do not roll over between billing periods unless stated in your plan. Subscription fees are billed in advance and are non-refundable except as set out in our <Link href="/refunds" className="text-purple-400 hover:text-purple-300 underline">Refund Policy</Link>.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">7. Service Availability</h2>
            <p>We aim for high availability but do not guarantee uninterrupted access. We may perform maintenance, updates, or experience downtime. We are not liable for losses arising from service interruptions.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">8. Limitation of Liability</h2>
            <p>To the maximum extent permitted by law, WizVid and its operators shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or goodwill, arising from your use of the Service. Our total liability to you for any claim shall not exceed the amount you paid us in the 12 months preceding the claim.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">9. Termination</h2>
            <p>We reserve the right to suspend or terminate your account at any time for violations of these Terms, with or without notice. You may cancel your account at any time from your account settings.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">10. Changes to Terms</h2>
            <p>We may update these Terms from time to time. Continued use of the Service after changes constitutes acceptance of the revised Terms. We will notify you of material changes by email.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">11. Governing Law</h2>
            <p>These Terms are governed by the laws of England and Wales. Any disputes shall be subject to the exclusive jurisdiction of the courts of England and Wales.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">12. Contact</h2>
            <p>For questions about these Terms, contact us at: <a href="mailto:support@wizvid.ai" className="text-purple-400 hover:text-purple-300 underline">support@wizvid.ai</a></p>
          </section>
        </div>
      </main>

      <footer className="border-t border-white/8 py-8 mt-16">
        <div className="max-w-4xl mx-auto px-6 flex flex-wrap gap-4 text-sm text-[#a1a1aa]">
          <Link href="/" className="hover:text-white transition-colors">Home</Link>
          <Link href="/privacy" className="hover:text-white transition-colors">Privacy Policy</Link>
          <Link href="/refunds" className="hover:text-white transition-colors">Refund Policy</Link>
          <a href="mailto:support@wizvid.ai" className="hover:text-white transition-colors">support@wizvid.ai</a>
        </div>
      </footer>
    </div>
  );
}
